version: '3.5'

services:
  app:
    image: 'docker-spring-boot:latest'
    build:
      context: .
    container_name: product-service-container
    environment:
      - integration_review-service_url=http://review-service-container:8082
    ports:
      - "127.0.0.1:8081:8081"
    networks:
      - product-review-network

networks:
  product-review-network:
    name: product-review-network
    driver: bridge